### ISSUE TITLE
render_bundle failing with TypeError: string indices must be integers

### ISSUE THREAD

**Issue by mikenowakme** [django-webpack/django-webpack-loader#227]
It seems that in webpack_loader/loader.filter_chunks, the chunks is an array of strings, not dictionaries with names and urls. How do I resolve this?

**Comment by oleggromov** [comment]
I am experiencing exactly same issue, exactly now 🤪

**Comment by oleggromov** [comment]
It seems that you have to roll back to https://github.com/owais/webpack-bundle-tracker/releases/tag/v0.4.3, which produces a different output.

**Comment by mikenowakme** [comment]
Rolling back to that older version did help me! I wonder if Django webpack needs to be updated for 1.0.0 of webpack-bundle-tracker.

**Comment by oleggromov** [comment]
I have created a fix and put it into a forked repo: https://github.com/oleggromov/django-webpack-loader/tree/support-webpack-bundle-tracker-1.0

If it proves to work fine, I'll make a PR.

**Comment by nhill-cpi** [comment]
@oleggromov Your fix works for me.

**Comment by owais** [comment]
@mikenowakme Yes, please use the stable version. Don't rely on the alpha for anything serious. Even when django-webpack-loader gets the update to work with 1.0-alpha of this package, it'll be released as an alpha as well. We'll announce when stable 1.0 is out for both packages.

**Comment by ajslater** [comment]
@owais the bug is in 0.7.0 on pypi, not just the alpha.

**Comment by Ammadkhalid** [comment]
i'm using latest version of it but i got to see the same error? here is my configs:

webpack.config.js:
```
const path = require('path');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const TerserJSPlugin = require('terser-webpack-plugin');
const OptimizeCSSAssetsPlugin = require('optimize-css-assets-webpack-plugin');
const {CleanWebpackPlugin} = require('clean-webpack-plugin');
const webpack = require("webpack");
const BundleTracker = require('webpack-bundle-tracker');
// const GoogleFontsPlugin = require("google-fonts-plugin");

// Set distribution path.
const DIST_PATH = path.resolve(__dirname, "static/assets/dist");
const IS_DEV_MODE = process.env.NODE_ENV !== 'production';

module.exports = {
    resolve: {
        extensions: [
            '.js', '.scss'
        ]
    },

    optimization: {
        minimizer: [
            new TerserJSPlugin({
                parallel: true,
                sourceMap: true,
                terserOptions: {
                    output: {
                        comments: false,
                    },
                },
            }),
            new OptimizeCSSAssetsPlugin({verbose: true}),
        ],
    },

    performance: {
        hints: 'warning',
    },

    entry: [
        './resources/assets/js/app.js',
        './resources/assets/css/app.scss'
    ],
    output: {
        path: DIST_PATH,
        filename: IS_DEV_MODE ? "app.js" : 'app.[hash].js'
    },
    mode: process.env.NODE_ENV,

    plugins: [
        new BundleTracker({
            path: __dirname,
        }),

        new MiniCssExtractPlugin({
            filename: IS_DEV_MODE ? 'app.css' : 'app.[hash].css',
            chunkFilename: IS_DEV_MODE ? '[id].css' : '[id].[hash].css',
            cssProcessorOptions: {
                safe: true,
                discardComments: {
                    removeAll: true,
                },
            },
        }),

        new webpack.ProvidePlugin({
            $: "jquery",
            jQuery: "jquery",
            Popper: ['popper.js', 'default']
        }),

        new CleanWebpackPlugin({verbose: true}),

        // new GoogleFontsPlugin({
        //     "fonts": [
        //         {
        //             "family": "Nunito",
        //             "variants": [
        //                 "400",
        //                 "300i"
        //             ],
        //             "subsets": [
        //                 "latin-ext"
        //             ]
        //         }
        //     ],
        //     "formats": [
        //         "woff",
        //         "woff2"
        //     ]
        // })

    ],
    module: {
        rules: [
            {
                test: /\.s[ac]ss$/i,
                use: [
                    {
                        loader: MiniCssExtractPlugin.loader,
                        options: {
                            publicPath: DIST_PATH
                        },
                    },
                    {
                        loader: 'css-loader',
                        // options: {
                        //   optimized: true
                        // }
                    },
                    'sass-loader',
                ],
            }
        ],
    },
};
```
webpack-stats.json
```
{
  "status": "done",
  "chunks": {
    "main": [
      "app.css",
      "app.js"
    ]
  },
  "assets": {
    "app.css": {
      "name": "app.css",
      "path": "/app/static/assets/dist/app.css"
    },
    "app.js": {
      "name": "app.js",
      "path": "/app/static/assets/dist/app.js"
    }
  }
}
```
SETTINGS
```
WEBPACK_LOADER = {
    'DEFAULT': {
        'CACHE': not DEBUG,
        'BUNDLE_DIR_NAME': 'assets/dist/',  # must end with slash
        'STATS_FILE': 'webpack-stats.json',
        'POLL_INTERVAL': 0.1,
        'TIMEOUT': None,
        'IGNORE': [r'.+\.hot-update.js', r'.+\.map'],
        'LOADER_CLASS': 'webpack_loader.loader.WebpackLoader',
    }
}
```

**Comment by Nyamador** [comment]
@Ammadkhalid you need to downgrade webpack-loader to  v0.4.3

**Comment by GitRon** [comment]
Just to clarify: You need to use in the `package.json` `webpack-bundle-tracker` v0.4.3.

**Comment by Nyamador** [comment]
That's a better one : )

**Comment by hasanparasteh** [comment]
Please, someone, fix this problem. I still get this error and I'm currently on the 0.4.3 version! here it's my package.json dependencies

```
"devDependencies": {
    "babel": "^6.23.0",
    "babel-loader": "^8.1.0",
    "concurrently": "^5.3.0",
    "webpack": "^5.3.2",
    "webpack-bundle-tracker": "^0.4.3",
    "webpack-cli": "^4.1.0"
  }
```

```
Environment:


Request Method: GET
Request URL: http://127.0.0.1:8000/brands/

Django Version: 3.1.2
Python Version: 3.6.7
Installed Applications:
['brands.apps.BrandsConfig',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'webpack_loader']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']


Template error:
In template E:\Hasan\Projects\sites\know-it\backend\src\templates\base.html, error at line 18
   string indices must be integers
   8 :     <meta name="viewport" content="width=device-width, initial-scale=1.0">
   9 : 
   10 :     <!--Title-->
   11 :     <title>Know it - {{title}}</title>
   12 : 
   13 :     <!--SEO-->
   14 : 
   15 : 
   16 :     <!--Styles-->
   17 :     <link href="https://fonts.googleapis.com/css2?family=Open+Sans&family=Rubik:ital,wght@0,700;0,900;1,400&display=swap" rel="stylesheet">
   18 :      {% render_bundle 'main' 'css' %} 
   19 : </head>
   20 : <body>
   21 :     <div class='main'>
   22 :         {% block content %}{% endblock content %}
   23 :     </div>
   24 : 
   25 :     <!--scripts-->
   26 :     {% render_bundle 'main' 'js' %}
   27 : </body>
   28 : </html>

Traceback (most recent call last):
  File "E:\Hasan\Projects\sites\know-it\backend\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\Hasan\Projects\sites\know-it\backend\env\lib\site-packages\django\core\handlers\base.py", line 202, in _get_response
    response = response.render()
  File "E:\Hasan\Projects\sites\know-it\backend\env\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "E:\Hasan\Projects\sites\know-it\backend\env\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "E:\Hasan\Projects\sites\know-it\backend\env\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\Hasan\Projects\sites\know-it\backend\env\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "E:\Hasan\Projects\sites\know-it\backend\env\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "E:\Hasan\Projects\sites\know-it\backend\env\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "E:\Hasan\Projects\sites\know-it\backend\env\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "E:\Hasan\Projects\sites\know-it\backend\env\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "E:\Hasan\Projects\sites\know-it\backend\env\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "E:\Hasan\Projects\sites\know-it\backend\env\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "E:\Hasan\Projects\sites\know-it\backend\env\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "E:\Hasan\Projects\sites\know-it\backend\env\lib\site-packages\django\template\library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "E:\Hasan\Projects\sites\know-it\backend\env\lib\site-packages\webpack_loader\templatetags\webpack_loader.py", line 12, in render_bundle
    tags = utils.get_as_tags(bundle_name, extension=extension, config=config, attrs=attrs)
  File "E:\Hasan\Projects\sites\know-it\backend\env\lib\site-packages\webpack_loader\utils.py", line 64, in get_as_tags
    for chunk in bundle:
  File "E:\Hasan\Projects\sites\know-it\backend\env\lib\site-packages\webpack_loader\utils.py", line 34, in _filter_by_extension
    for chunk in bundle:
  File "E:\Hasan\Projects\sites\know-it\backend\env\lib\site-packages\webpack_loader\loader.py", line 43, in filter_chunks
    for regex in self.config['ignores'])
  File "E:\Hasan\Projects\sites\know-it\backend\env\lib\site-packages\webpack_loader\loader.py", line 43, in <genexpr>
    for regex in self.config['ignores'])

Exception Type: TypeError at /brands/
Exception Value: string indices must be integers
```

**Comment by nirvaansingh47** [comment]
@hasanparasteh If you still facing this issue, it may be because your django project is pointing to the wrong webpack-stats.json file. Note that the below is not pointing to the dist folder (where the latest version of webpack-bundle-tracker creates the webpack-stats.json file) rather the root of the frontend project. 

`WEBPACK_LOADER = {
    'DEFAULT': {
        'BUNDLE_DIR_NAME': 'dist/',
        'STATS_FILE': os.path.join(BASE_DIR, 'frontend', 'webpack-stats.json'),
    }
}`

**Comment by Fethienv** [comment]
Hi
I made the following changes on loader.py and it worked for me:
`
    def filter_chunks(self, chunks):
        for chunk in chunks:
            if isinstance(chunk, dict):
                new_chunk = chunk
            else:
                new_chunk = {
                    'name': chunk
                }

            ignore = any(regex.match(new_chunk['name'])
                         for regex in self.config['ignores'])
            if not ignore:
                new_chunk['url'] = self.get_chunk_url(new_chunk)
                yield new_chunk

`

**Comment by hasanparasteh** [comment]
> Hi
> I made the following changes on loader.py and it worked for me:
> 
> ```
>     def filter_chunks(self, chunks):
>         for chunk in chunks:
>             if isinstance(chunk, dict):
>                 new_chunk = chunk
>             else:
>                 new_chunk = {
>                     "name": chunk
>                 }
> 
>             ignore = any(regex.match(new_chunk["name"])
>                          for regex in self.config["ignores"])
>             if not ignore:
>                 new_chunk["url"] = self.get_chunk_url(new_chunk)
>                 yield new_chunk
> ```

Thanks, it's fixed now...

**Comment by jillesme** [comment]
Thanks @Fethienv, I got it working using your solution but slightly modified.

```python
# app/webpack.py
from webpack_loader.loader import WebpackLoader

class CustomWebpackLoader(WebpackLoader):
    def filter_chunks(self, chunks):
        chunks = [chunk if isinstance(chunk, dict) else {'name': chunk} for chunk in chunks]
        return super().filter_chunks(chunks)

# settings.py
WEBPACK_LOADER = {
    ...
    'LOADER_CLASS': 'app.webpack.CustomWalkLoader',
}
```

**Comment by n6151h** [comment]
> Just to clarify: You need to use in the `package.json` `webpack-bundle-tracker` v0.4.3.

Did this.  
Still doesn't work.
Now getting "Cannot resolve bundle ____", whether I'm using "app", "main", "vendor", whatever.

**Comment by nerdoc** [comment]
@owais Is there a chance that you fix that in webpack_loader?  @Fethienv's solution seems to work - and django-webpack_loader is unusable ATM, just by installing it and webpack-bundle-tracker on the Js side, without patches and without using an old version, does just not work.

**Comment by vabene1111** [comment]
Ok so i have run into the same problem updating from 0.4.3 to 1. alpha (because i needed the relative path feature of the new version).

In addition to the awesome solution provided by @jillesme i have added one more function to the custom loader to support hot reloading again as the publicPath variable that was previously included in the chunk directly is now contained in the assets key of the json

```python
class CustomWebpackLoader(WebpackLoader):
    def get_chunk_url(self, chunk):
        asset = self.get_assets()['assets'][chunk['name']]
        return super().get_chunk_url(asset)

    def filter_chunks(self, chunks):
        chunks = [chunk if isinstance(chunk, dict) else {'name': chunk} for chunk in chunks]
        return super().filter_chunks(chunks)
```
I have not tested this too much but it appears to restore the old behavior which makes sense from the old and new json formats. For future reference

Old Build Format
```json
"status": "done",
  "chunks": {
    "chunk-vendors": [
      {
        "name": "css/chunk-vendors.css",
        "path": "full\\path\\to\\application\\static\\vue\\css\\chunk-vendors.css"
      },
    ],
```

Old DEV/Hot reload Format
```json
"status": "done",
  "chunks": {
    "chunk-vendors": [
      {
        "name": "css/chunk-vendors.css",
        "path": "full\\path\\to\\application\\static\\vue\\css\\chunk-vendors.css",
        "publicPath": "http://localhost:8080/js/chunk-vendors.js"
      },
    ],
```

New DEV/HotFormat
```json
{
  "status": "done",
  "chunks": {
    "view_name": [
      "css/chunk-vendors.css",
      "js/chunk-vendors.js",
      "js/view_name.js"
    ],
  },
  "assets": {
    "css/chunk-vendors.css": {
      "name": "css/chunk-vendors.css",
      "path": ""full\\path\\to\\application\\static\\vue\\css\\chunk-vendors.css"
    },
```

New Build Format
```json
{
  "status": "done",
  "chunks": {
    "view_name": [
      "js/chunk-vendors.js",
      "js/view_name.js"
    ],
  },
  "publicPath": "http://localhost:8080/",
  "assets": {
    "js/chunk-vendors.js": {
      "name": "js/chunk-vendors.js",
       "path": ""full\\path\\to\\application\\static\\vue\\css\\chunk-vendors.css"
      "publicPath": "http://localhost:8080/js/chunk-vendors.js"
    },
```

The same structure applies to the relativePath option set to true which simply replaces the full "path" key with a relative one. A fully working example can be found in the application i use this package with https://github.com/vabene1111/recipes

**Comment by hjw21century** [comment]
> It seems that you have to roll back to https://github.com/owais/webpack-bundle-tracker/releases/tag/v0.4.3, which produces a different output.
> 
> **UPDATE:** Unfortunately, this doesn't solve the issue entirely. With 0.4.3, `webpack-bundle-tracker` produces the following output with code splitting on my project:
> 
> ```
> {
>   "status": "done",
>   "publicPath": "/",
>   "chunks": {
>     "main": [{
>       "name": "main.242b239a.js",
>       "publicPath": "/main.242b239a.js",
>       "path": "{HERE_WAS_ABSOLUTE_PATH}/frontend/dist/main.242b239a.js"
>     }, {
>       "name": "main.242b239a.js.map",
>       "publicPath": "/main.242b239a.js.map",
>       "path": "{HERE_WAS_ABSOLUTE_PATH}/frontend/dist/main.242b239a.js.map"
>     }],
>     "runtime-main": [{
>       "name": "runtime-main.55f44f0e.js",
>       "publicPath": "/runtime-main.55f44f0e.js",
>       "path": "{HERE_WAS_ABSOLUTE_PATH}/frontend/dist/runtime-main.55f44f0e.js"
>     }, {
>       "name": "runtime-main.55f44f0e.js.map",
>       "publicPath": "/runtime-main.55f44f0e.js.map",
>       "path": "{HERE_WAS_ABSOLUTE_PATH}/frontend/dist/runtime-main.55f44f0e.js.map"
>     }],
>     "undefined": [{
>       "name": "2.24aa6e52.js",
>       "publicPath": "/2.24aa6e52.js",
>       "path": "{HERE_WAS_ABSOLUTE_PATH}/frontend/dist/2.24aa6e52.js"
>     }, {
>       "name": "2.24aa6e52.js.map",
>       "publicPath": "/2.24aa6e52.js.map",
>       "path": "{HERE_WAS_ABSOLUTE_PATH}/frontend/dist/2.24aa6e52.js.map"
>     }]
>   }
> }
> ```
> 
> Note first-level keys in `chunks` - one of them is even `undefined`. The newer version `1.0.0-alpha.1` produces the following:
> 
> ```
> {
>   "status": "done",
>   "chunks": {
>     "main": ["runtime-main.55f44f0e.js", "runtime-main.55f44f0e.js.map", "2.24aa6e52.js", "2.24aa6e52.js.map", "main.242b239a.js", "main.242b239a.js.map"]
>   },
>   "publicPath": "/",
>   "assets": {
>     "main.242b239a.js": {
>       "name": "main.242b239a.js",
>       "path": "{ABSOLUTE_PATH_WAS_HERE}/frontend/dist/main.242b239a.js",
>       "publicPath": "/main.242b239a.js"
>     },
>     "runtime-main.55f44f0e.js": {
>       "name": "runtime-main.55f44f0e.js",
>       "path": "{ABSOLUTE_PATH_WAS_HERE}/frontend/dist/runtime-main.55f44f0e.js",
>       "publicPath": "/runtime-main.55f44f0e.js"
>     },
>     "2.24aa6e52.js": {
>       "name": "2.24aa6e52.js",
>       "path": "{ABSOLUTE_PATH_WAS_HERE}/frontend/dist/2.24aa6e52.js",
>       "publicPath": "/2.24aa6e52.js"
>     },
>     "2.24aa6e52.js.LICENSE.txt": {
>       "name": "2.24aa6e52.js.LICENSE.txt",
>       "path": "{ABSOLUTE_PATH_WAS_HERE}/frontend/dist/2.24aa6e52.js.LICENSE.txt",
>       "publicPath": "/2.24aa6e52.js.LICENSE.txt"
>     },
>     "main.242b239a.js.map": {
>       "name": "main.242b239a.js.map",
>       "path": "{ABSOLUTE_PATH_WAS_HERE}/frontend/dist/main.242b239a.js.map",
>       "publicPath": "/main.242b239a.js.map"
>     },
>     "runtime-main.55f44f0e.js.map": {
>       "name": "runtime-main.55f44f0e.js.map",
>       "path": "{ABSOLUTE_PATH_WAS_HERE}/frontend/dist/runtime-main.55f44f0e.js.map",
>       "publicPath": "/runtime-main.55f44f0e.js.map"
>     },
>     "2.24aa6e52.js.map": {
>       "name": "2.24aa6e52.js.map",
>       "path": "{ABSOLUTE_PATH_WAS_HERE}/frontend/dist/2.24aa6e52.js.map",
>       "publicPath": "/2.24aa6e52.js.map"
>     }
>   }
> }
> ```
> 
> Now we'll need to traverse `chunks.main` independently `assets`. I believe this shall be an easy fix - if I happen to fix it for my own use, I'll make a PR.

It is a problem with the django-webpack-loader version.
